### ISSUE TITLE
'kniprot_cocoapods_PurchasesHybridCommonUI1_RCPaywallViewControllerDelegateWrapper': symbol multiply defined!

### ISSUE THREAD

**Issue by hellosagar** [RevenueCat/purchases-kmp#357]
- [x] I have updated Purchases SDK to the latest version
- [x] I have read
  the [Contribution Guidelines](https://github.com/RevenueCat/purchases-android/blob/main/CONTRIBUTING.md)
- [x] I have searched the [Community](https://community.revenuecat.com)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched
  for [existing Github issues](https://github.com/RevenueCat/purchases-kmp/issues)

**Describe the bug**
where the revenue cat v2 paywall is working well with version `1.5.1+13.18.1` but only for android, on iOS its failing with an error below

```

Showing All Errors Only
Compilation failed: Linking globals named 'kniprot_cocoapods_PurchasesHybridCommonUI1_RCPaywallViewControllerDelegateWrapper': symbol multiply defined!

java.lang.Error: Linking globals named 'kniprot_cocoapods_PurchasesHybridCommonUI1_RCPaywallViewControllerDelegateWrapper': symbol multiply defined!


```

and this my cocoapods block from build.gradle.kts

```kts
cocoapods {
        // Required fields
        version = "1.0"
        summary = "Some description for a Kotlin/Native module"
        homepage = "Link to a Kotlin/Native module homepage"

        // Match target in Podfile
        ios.deploymentTarget = "15.4"

        // Specify path to Podfile
        podfile = project.file("../iosApp/Podfile")

        framework {
            baseName = "ComposeApp"
            isStatic = true
        }

        pod("Mixpanel") {
            extraOpts += listOf("-compiler-option", "-fmodules")
        }

        pod("PurchasesHybridCommon") {
            version = libs.versions.purchases.common.get()
            extraOpts += listOf("-compiler-option", "-fmodules")
        }

        pod("PurchasesHybridCommonUI") {
            version = libs.versions.purchases.common.get()
            extraOpts += listOf("-compiler-option", "-fmodules")
        }

        xcodeConfigurationToNativeBuildType["CUSTOM_DEBUG"] = NativeBuildType.DEBUG
        xcodeConfigurationToNativeBuildType["CUSTOM_RELEASE"] = NativeBuildType.RELEASE
    }
```

and this is my Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'composeApp', :path => '../composeApp'
    pod 'Firebase/Core', '11.5.0'
    pod 'Firebase/Crashlytics', '11.5.0'
    pod 'Firebase/Analytics', '11.5.0'
    pod 'Firebase/Performance', '11.5.0'
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleUserMessagingPlatform'

  # Pods for iosApp

  # Add the following post_install script:
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'composeApp'
        target.build_configurations.each do |config|
          config.build_settings.delete('ASSETCATALOG_COMPILER_APPICON_NAME')
        end
      end
    end
  end
end

```

1. Environment
    1. Platform: Compose Multiplatform
    2. SDK version: 
    3. AGP: 8.5.2
    3. Kotlin: 2.1.0
    3. OS version: Sonoma 14.6.1 (23G93)
    4. IDE (e.g. Android Studio, Xcode, Fleet): Android
    5. IDE version: Android Studio Meerkat | 2024.3.1
    6. Device and/or emulator/simulator:
        - [ ] Device
        - [ ] Emulator/simulator
    7. Environment:
        - [ ] Closed testing / Sandbox
        - [ ] TestFlight
        - [ ] Production
    8. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to
   have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by JayShortway** [comment]
Thanks for reporting this! Just tagging an issue that seems similar, in case it's helpful: https://github.com/RevenueCat/purchases-kmp/issues/336. 

The error indicates that `PurchasesHybridCommonUI` is included in your app twice. By any chance, did you add it in any other way as well, such as in Xcode?

**Comment by JayShortway** [comment]
>Interestingly, when I removed PurchasesHybridCommon and kept only PurchasesHybridCommonUI, the Gradle sync was successful. However, on iOS, the app crashed on startup.

This is interesting info, thanks! Glad to hear the issue got resolved.

I'll close this for now, but feel free to reopen.
